---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-enable-etcd-encryption
  namespace: compliance-operator-policies
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    policy.open-cluster-management.io/standards: SOC 2, NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-13 Cryptographic Protection, SC-8 Transmission Confidentiality and Integrity, CC6.6 Encryption at Rest, CC6.7 Transmission Protection
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: enable-etcd-encryption
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: APIServer
                metadata:
                  name: cluster
                spec:
                  encryption:
                    type: aescbc
                  tlsSecurityProfile:
                    type: Intermediate

